name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq lua5.1 luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: make luacheck
      